## Runtime execution helpers for nsql.
##
## These procs are called by the code generated by the nsql plugin.
## They wrap the raw SQLite FFI into type-safe operations.

{.feature: "lenientnils".}

import nsql/sqlite3

# ---- Connection management ----

proc openDatabase*(path: string): DbConn =
  var db: DbConn = nil
  var pathMut = path
  let rc = sqlite3_open_v2(
    toCString(pathMut),
    db,
    cint(SQLITE_OPEN_READWRITE or SQLITE_OPEN_CREATE),
    nil
  )
  if rc != SQLITE_OK:
    # Can't use exceptions yet (Nimony), so write to stderr and quit
    # TODO: proper error handling
    discard sqlite3_close_v2(db)
    db = nil
  result = db

proc closeDatabase*(db: DbConn) =
  discard sqlite3_close_v2(db)

# ---- Statement lifecycle ----

proc prepareStmt*(db: DbConn, sql: string): Stmt =
  var stmt: Stmt = nil
  var sqlMut = sql
  let rc = sqlite3_prepare_v2(db, toCString(sqlMut), sqlMut.len.cint, stmt, nil)
  if rc != SQLITE_OK:
    stmt = nil
  result = stmt

proc finalizeStmt*(stmt: Stmt) =
  discard sqlite3_finalize(stmt)

proc stepStmt*(stmt: Stmt): cint =
  result = sqlite3_step(stmt)

# ---- Parameter binding ----

proc bindInt64*(stmt: Stmt, idx: int, value: int64): bool =
  result = sqlite3_bind_int64(stmt, idx.cint, value) == SQLITE_OK

proc bindText*(stmt: Stmt, idx: int, value: string): bool =
  var valMut = value
  result = sqlite3_bind_text(stmt, idx.cint, toCString(valMut), valMut.len.cint, cast[pointer](-1)) == SQLITE_OK

proc bindFloat64*(stmt: Stmt, idx: int, value: float64): bool =
  result = sqlite3_bind_double(stmt, idx.cint, value) == SQLITE_OK

# ---- Overloaded bindParam — the plugin generates calls to these ----
# The compiler picks the right overload based on the argument type at the call site.

proc bindParam*(stmt: Stmt, idx: int, value: int64) =
  discard sqlite3_bind_int64(stmt, idx.cint, value)

proc bindParam*(stmt: Stmt, idx: int, value: string) =
  var valMut = value
  discard sqlite3_bind_text(stmt, idx.cint, toCString(valMut), valMut.len.cint, cast[pointer](-1))

proc bindParam*(stmt: Stmt, idx: int, value: float64) =
  discard sqlite3_bind_double(stmt, idx.cint, value)

# ---- Column value extraction ----

proc columnInt64*(stmt: Stmt, col: int): int64 =
  result = sqlite3_column_int64(stmt, col.cint)

proc columnString*(stmt: Stmt, col: int): string =
  let cstr = sqlite3_column_text(stmt, col.cint)
  if cstr != nil:
    result = fromCString(cstr)
  else:
    result = ""

proc columnFloat64*(stmt: Stmt, col: int): float64 =
  result = sqlite3_column_double(stmt, col.cint)

# ---- Misc ----

proc execSql*(db: DbConn, sql: string): bool =
  var sqlMut = sql
  result = sqlite3_exec(db, toCString(sqlMut), nil, nil, nil) == SQLITE_OK

proc lastInsertRowid*(db: DbConn): int64 =
  result = sqlite3_last_insert_rowid(db)

proc changes*(db: DbConn): int64 =
  result = sqlite3_changes(db).int64
