## Runtime execution helpers for nsql.
##
## These procs are called by the code generated by the nsql plugin.
## They wrap the raw SQLite FFI into type-safe operations.

{.feature: "lenientnils".}

import sqlite3

template sqliteTransient(): pointer =
  cast[pointer](-1)

proc stringBytes(s: string): cstring {.inline.} =
  cast[cstring](readRawData(s))

# ---- Connection management ----

proc openDatabaseCString*(path: cstring): DbConn =
  var db: DbConn = nil
  let rc = sqlite3_open_v2(
    path,
    db,
    cint(SQLITE_OPEN_READWRITE or SQLITE_OPEN_CREATE),
    nil
  )
  if rc != SQLITE_OK:
    # Can't use exceptions yet (Nimony), so write to stderr and quit
    # TODO: proper error handling
    discard sqlite3_close_v2(db)
    db = nil
  result = db

proc openDatabase*(path: string): DbConn =
  # SQLite's filename API is NUL-terminated only, so dynamic strings need one
  # materialized cstring boundary. Length-counted SQL/text paths avoid this.
  var pathMut = path
  result = openDatabaseCString(toCString(pathMut))

proc closeDatabase*(db: DbConn) =
  discard sqlite3_close_v2(db)

# ---- Statement lifecycle ----

proc prepareStmtBytes*(db: DbConn, sql: cstring, sqlLen: int): Stmt =
  var stmt: Stmt = nil
  let rc = sqlite3_prepare_v2(db, sql, sqlLen.cint, stmt, nil)
  if rc != SQLITE_OK:
    stmt = nil
  result = stmt

template prepareStmtSql*(db: DbConn, sql: typed, sqlLen: int): Stmt =
  prepareStmtBytes(db, cstring(sql), sqlLen)

proc prepareStmt*(db: DbConn, sql: string): Stmt =
  result = prepareStmtBytes(db, stringBytes(sql), sql.len)

proc finalizeStmt*(stmt: Stmt) =
  discard sqlite3_finalize(stmt)

proc stepStmt*(stmt: Stmt): cint =
  result = sqlite3_step(stmt)

# ---- Parameter binding ----

proc bindInt64*(stmt: Stmt, idx: int, value: int64): bool =
  result = sqlite3_bind_int64(stmt, idx.cint, value) == SQLITE_OK

proc bindText*(stmt: Stmt, idx: int, value: string): bool =
  result = sqlite3_bind_text(
    stmt,
    idx.cint,
    stringBytes(value),
    value.len.cint,
    sqliteTransient()
  ) == SQLITE_OK

proc bindFloat64*(stmt: Stmt, idx: int, value: float64): bool =
  result = sqlite3_bind_double(stmt, idx.cint, value) == SQLITE_OK

# ---- Overloaded bindParam — the plugin generates calls to these ----
# The compiler picks the right overload based on the argument type at the call site.

proc bindParam*(stmt: Stmt, idx: int, value: int64) =
  discard sqlite3_bind_int64(stmt, idx.cint, value)

proc bindParam*(stmt: Stmt, idx: int, value: string) =
  discard sqlite3_bind_text(
    stmt,
    idx.cint,
    stringBytes(value),
    value.len.cint,
    sqliteTransient()
  )

proc bindParam*(stmt: Stmt, idx: int, value: float64) =
  discard sqlite3_bind_double(stmt, idx.cint, value)

# ---- Column value extraction ----

proc columnInt64*(stmt: Stmt, col: int): int64 =
  result = sqlite3_column_int64(stmt, col.cint)

proc columnString*(stmt: Stmt, col: int): string =
  let cstr = sqlite3_column_text(stmt, col.cint)
  if cstr != nil:
    result = fromCString(cstr)
  else:
    result = ""

proc columnFloat64*(stmt: Stmt, col: int): float64 =
  result = sqlite3_column_double(stmt, col.cint)

# ---- Misc ----

proc execSql*(db: DbConn, sql: string): bool =
  let stmt = prepareStmt(db, sql)
  if stmt == nil:
    return false

  let rc = sqlite3_step(stmt)
  discard sqlite3_finalize(stmt)
  result = rc == SQLITE_DONE or rc == SQLITE_ROW

proc lastInsertRowid*(db: DbConn): int64 =
  result = sqlite3_last_insert_rowid(db)

proc changes*(db: DbConn): int64 =
  result = sqlite3_changes(db).int64
